### ISSUE TITLE
Nightcore

### ISSUE THREAD

**Issue by KRDucky** [JoeZwet/ncsBot#2]
Please add the NCS Nightcore Genre to Music Types.

**Comment by JoeZwet** [comment]
link please

**Comment by KRDucky** [comment]
https://www.youtube.com/channel/UCZdC2vQmgdf97CeXU1Tq_0w

**Comment by KRDucky** [comment]
it is his new Nightcore channel.

**Comment by JoeZwet** [comment]
I'll add in 2.9

**Comment by JoeZwet** [comment]
added
