### ISSUE TITLE
Disconect issue

### ISSUE THREAD

**Issue by Reddox2** [JoeZwet/ncsBot#3]
Hi, I have an issue with the ncs bot, he disconnects from my server, and I can't go him back. Please fix !

**Comment by JoeZwet** [comment]
did it leave your server or is it just offline
because its been offline for while, but its back up now

**Comment by Reddox2** [comment]
He was offline,  he's back now thx. How can I put him back online if it happens another time?

**Comment by JoeZwet** [comment]
message me on discord because i have to access the server to start it again
